Metadata: 
  License: Apache-2.0  # Specifies the license for this CloudFormation template
AWSTemplateFormatVersion: '2010-09-09'  # Version of CloudFormation being used
Description: >
  AWS CloudFormation Sample Template EIP_With_Association:
  This template shows how to associate an Elastic IP address with an Amazon EC2 instance.
  You may associate an EC2 instance with an Elastic IP Address that is not created 
  inside the template by replacing the EIP reference in the 
  AWS::EC2::EIPAssociation resource type with the external EIP's address.
  **WARNING** This template creates an Amazon EC2 instance and an Elastic IP Address.
  You will be billed for the AWS resources used if you create a stack from this template.

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type  # Type of EC2 instance to be launched
    Type: String
    Default: t3.small  # Default instance type
    AllowedValues: 
      # List of allowed instance types
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - g3.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access  # KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances  # IP range for SSH access
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0  # Allows SSH access from any IP by default (not secure in production)
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'  # Latest Amazon Linux 2 AMI

Resources:
  # EC2 Instance resource definition
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      UserData: !Base64
        Fn::Join:
          - ''
          - [IPAddress=, !Ref 'IPAddress']  # Passes the EIP as user data (not typically used this way)
      InstanceType: !Ref 'InstanceType'  # Instance type from parameters
      SecurityGroups: [!Ref 'InstanceSecurityGroup']  # Security group for the instance
      KeyName: !Ref 'KeyName'  # KeyPair for the instance
      ImageId: !Ref 'LatestAmiId'  # AMI ID for the instance

  # Security group allowing SSH access
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access  # Description of the security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref 'SSHLocation'  # Allows SSH access from the specified IP range

  # Elastic IP address for the instance
  IPAddress:
    Type: AWS::EC2::EIP

  # Associates the Elastic IP with the EC2 instance
  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'EC2Instance'  # ID of the EC2 instance
      EIP: !Ref 'IPAddress'  # The Elastic IP to associate

Outputs:
  # Output the instance ID of the created EC2 instance
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  
  # Output the Elastic IP address associated with the EC2 instance
  InstanceIPAddress:
    Description: IP address of the newly created EC2 instance
    Value: !Ref 'IPAddress'
