Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>  # Parameter type that retrieves the AMI ID from the SSM Parameter Store
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2  # Default value pointing to the latest Amazon Linux 2 AMI

Resources:
  MyEC2Instance:  # Define the EC2 instance resource
    Type: AWS::EC2::Instance  # Resource type for creating an EC2 instance
    Properties:
      InstanceType: t2.micro  # Specifies the instance type; t2.micro is eligible for the AWS Free Tier
      ImageId: !Ref ImageId  # Use the AMI ID retrieved from the ImageId parameter to launch the instance
